<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link href="/fiam_gare/css/style.css"  rel="stylesheet" type="text/css" />

<!-- CHECKBOX -->
<link rel="stylesheet" type="text/css" href="form.css" />
	
	<script type="text/javascript" src="custom-form-elements.js"></script>

<!-- FINE CHECKBOX -->
 <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine|Inconsolata|Droid+Sans">
 <link href='http://fonts.googleapis.com/css?family=Orbitron:regular,500,bold,900' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Syncopate' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Josefin+Sans:100,100italic,light,lightitalic,regular,regularitalic,600,600italic,bold,bolditalic' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Geo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Crushed' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu:regular,italic,bold,bolditalic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Italianno' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Voltaire' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nothing+You+Could+Do' rel='stylesheet' type='text/css'>

<title>Event registration</title>
<script type="text/javascript">
<!--
var newid = 10;
var numriga = 0;

function aggiungiCampi() {
	var t = document.getElementById('atleti');
	for(i=0; i<10; i++){
		var node=document.createElement("tr");
		node.innerHTML=	creaRiga(newid);
		numriga++;
		node.className="riga"+numriga;
		newid++;
		numriga = numriga % 2;
		t.appendChild(node);
	}
}

function creaRiga(id) {
	return '<td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[' + id + ']" value="' + id + '" /></td><td class="cognome"><input type="text"   name="cognome[' + id + ']" value=""/></td><td class="nome"><input type="text"   name="nome[' + id + ']" value=""/></td><td class="sesso"><select name="sesso[' + id + ']"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[' + id + ']" value=""/></td><td class="cinture"><select name="newcintura[' + id + ']"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[' + id + '][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[' + id + '][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[' + id + '][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[' + id + ']"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[' + id + ']" value=""/></td>';
}
-->
</script>
<style>
tr.err {
background-color: yellow;
}

.err {
background-color: red;
}

</style>
</head>

<body>

<div align="center">
<div id="box">
<div id="head">
<div id="logo" style="margin-right:100px"> <img src="/fiam_gare/img/logo.png" height="96%" ></img> </div>

<h1>Event registration</h1>

<h2>Prima gara</h2>

</div>

<div id="form_login">
<form action="/fiam_gare/soc/iscrivi.php?id=1" method="post">
	<input type="hidden" name="pageid" value="563a0635a4f088fa43519fb0d7c2b95b" />
	
	<div class="pulsante tr">
	<input type="submit" value="Save" />
</div>
<br></br>
<table  id="atleti">
<tr  class="tr">

<th></th>
<th><div class='thAtleti'>Family Name</div></th>
<th><div class='thAtleti'>Given Name</div></th>
<th><div class="thAtleti" >Gender</div></th>
<th><div class='thAtleti'>Birth date</div></th>
<th><div class='thAtleti'>Belt</div></th>
<th><div class="thAtleti" >Kata</div></th>
<th><div class="thAtleti">Sanbon</div></th>
<th><div class="thAtleti">Ippon</div></th>
<th><div class='thAtleti'>Style</div></th>
<th><div class='thAtleti'>Weight</div></th>


</tr>



<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="check[13]" value="13" checked="checked" /></td><td class="cognome">Atkinson</td><td class="nome">Sharon</td><td class="sesso">F</td><td class="nascita">14/04/1996</td><td class="cinture"><select name="cintura[13]"><option value="1" selected="selected">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[13][0]" value="0" checked="checked" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[13][1]" value="1" disabled="disabled" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[13][2]" value="2" disabled="disabled" alt="Ippon" /></td><td class="stile"><select name="stile[13]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[13]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="check[20]" value="20" checked="checked" /></td><td class="cognome">Bell</td><td class="nome">Desirae</td><td class="sesso">F</td><td class="nascita">14/06/1993</td><td class="cinture"><select name="cintura[20]"><option value="1" selected="selected">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[20][0]" value="0" checked="checked" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[20][1]" value="1" disabled="disabled" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[20][2]" value="2" disabled="disabled" alt="Ippon" /></td><td class="stile"><select name="stile[20]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[20]" value=""/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="check[36]" value="36" /></td><td class="cognome">d</td><td class="nome">gr</td><td class="sesso">M</td><td class="nascita">04/02/1998</td><td class="cinture"><select name="cintura[36]"><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6" selected="selected">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[36][0]" value="0" disabled="disabled" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[36][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[36][2]" value="2" disabled="disabled" alt="Ippon" /></td><td class="stile"><select name="stile[36]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[36]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="check[5]" value="5" checked="checked" /></td><td class="cognome">Gomez</td><td class="nome">Henry</td><td class="sesso">M</td><td class="nascita">12/10/1979</td><td class="cinture"><select name="cintura[5]"><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6" selected="selected">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[5][0]" value="0" disabled="disabled" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[5][1]" value="1" checked="checked" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[5][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="stile[5]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[5]" value="65"/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="check[39]" value="39" checked="checked" /></td><td class="cognome">new</td><td class="nome">atl</td><td class="sesso">F</td><td class="nascita">04/02/1998</td><td class="cinture"><select name="cintura[39]"><option value="1" selected="selected">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[39][0]" value="0" checked="checked" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[39][1]" value="1" disabled="disabled" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[39][2]" value="2" disabled="disabled" alt="Ippon" /></td><td class="stile"><select name="stile[39]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[39]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="check[3]" value="3" /></td><td class="cognome">Newman</td><td class="nome">Adam</td><td class="sesso">M</td><td class="nascita">17/06/1978</td><td class="cinture"><select name="cintura[3]"><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6" selected="selected">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[3][0]" value="0" disabled="disabled" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[3][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[3][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="stile[3]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[3]" value=""/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="check[6]" value="6" /></td><td class="cognome">Porter</td><td class="nome">Preston</td><td class="sesso">M</td><td class="nascita">26/02/1997</td><td class="cinture"><select name="cintura[6]"><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6" selected="selected">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[6][0]" value="0" disabled="disabled" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[6][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[6][2]" value="2" disabled="disabled" alt="Ippon" /></td><td class="stile"><select name="stile[6]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[6]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="check[37]" value="37" checked="checked" /></td><td class="cognome">rossi</td><td class="nome">mario</td><td class="sesso">M</td><td class="nascita">12/10/1979</td><td class="cinture"><select name="cintura[37]"><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6" selected="selected">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[37][0]" value="0" disabled="disabled" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[37][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[37][2]" value="2" checked="checked" alt="Ippon" /></td><td class="stile"><select name="stile[37]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[37]" value=""/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="check[38]" value="38" checked="checked" /></td><td class="cognome">verdi</td><td class="nome">luigi</td><td class="sesso">M</td><td class="nascita">04/08/1980</td><td class="cinture"><select name="cintura[38]"><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5" selected="selected">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[38][0]" value="0" disabled="disabled" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[38][1]" value="1" checked="checked" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[38][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="stile[38]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[38]" value="60"/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="check[2]" value="2" /></td><td class="cognome">Weeks</td><td class="nome">Connor</td><td class="sesso">M</td><td class="nascita">04/02/1998</td><td class="cinture"><select name="cintura[2]"><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6" selected="selected">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[2][0]" value="0" disabled="disabled" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[2][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="tipo[2][2]" value="2" disabled="disabled" alt="Ippon" /></td><td class="stile"><select name="stile[2]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="peso[2]" value=""/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[0]" value="0" /></td><td class="cognome"><input type="text"   name="cognome[0]" value=""/></td><td class="nome"><input type="text"   name="nome[0]" value=""/></td><td class="sesso"><select name="sesso[0]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[0]" value=""/></td><td class="cinture"><select name="newcintura[0]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[0][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[0][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[0][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[0]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[0]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[1]" value="1" /></td><td class="cognome"><input type="text"   name="cognome[1]" value=""/></td><td class="nome"><input type="text"   name="nome[1]" value=""/></td><td class="sesso"><select name="sesso[1]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[1]" value=""/></td><td class="cinture"><select name="newcintura[1]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[1][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[1][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[1][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[1]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[1]" value=""/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[2]" value="2" /></td><td class="cognome"><input type="text"   name="cognome[2]" value=""/></td><td class="nome"><input type="text"   name="nome[2]" value=""/></td><td class="sesso"><select name="sesso[2]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[2]" value=""/></td><td class="cinture"><select name="newcintura[2]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[2][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[2][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[2][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[2]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[2]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[3]" value="3" /></td><td class="cognome"><input type="text"   name="cognome[3]" value=""/></td><td class="nome"><input type="text"   name="nome[3]" value=""/></td><td class="sesso"><select name="sesso[3]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[3]" value=""/></td><td class="cinture"><select name="newcintura[3]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[3][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[3][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[3][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[3]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[3]" value=""/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[4]" value="4" /></td><td class="cognome"><input type="text"   name="cognome[4]" value=""/></td><td class="nome"><input type="text"   name="nome[4]" value=""/></td><td class="sesso"><select name="sesso[4]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[4]" value=""/></td><td class="cinture"><select name="newcintura[4]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[4][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[4][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[4][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[4]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[4]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[5]" value="5" /></td><td class="cognome"><input type="text"   name="cognome[5]" value=""/></td><td class="nome"><input type="text"   name="nome[5]" value=""/></td><td class="sesso"><select name="sesso[5]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[5]" value=""/></td><td class="cinture"><select name="newcintura[5]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[5][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[5][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[5][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[5]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[5]" value=""/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[6]" value="6" /></td><td class="cognome"><input type="text"   name="cognome[6]" value=""/></td><td class="nome"><input type="text"   name="nome[6]" value=""/></td><td class="sesso"><select name="sesso[6]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[6]" value=""/></td><td class="cinture"><select name="newcintura[6]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[6][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[6][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[6][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[6]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[6]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[7]" value="7" /></td><td class="cognome"><input type="text"   name="cognome[7]" value=""/></td><td class="nome"><input type="text"   name="nome[7]" value=""/></td><td class="sesso"><select name="sesso[7]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[7]" value=""/></td><td class="cinture"><select name="newcintura[7]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[7][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[7][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[7][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[7]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[7]" value=""/></td></tr>
<tr class="riga1"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[8]" value="8" /></td><td class="cognome"><input type="text"   name="cognome[8]" value=""/></td><td class="nome"><input type="text"   name="nome[8]" value=""/></td><td class="sesso"><select name="sesso[8]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[8]" value=""/></td><td class="cinture"><select name="newcintura[8]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[8][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[8][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[8][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[8]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[8]" value=""/></td></tr>
<tr class="riga2"><td class="iscr_check"><input type="checkbox" class="styled" name="newcheck[9]" value="9" /></td><td class="cognome"><input type="text"   name="cognome[9]" value=""/></td><td class="nome"><input type="text"   name="nome[9]" value=""/></td><td class="sesso"><select name="sesso[9]"><option value="0"></option><option value="1">M</option><option value="2">F</option></select></td><td class="nascita"><input type="text"   name="nascita[9]" value=""/></td><td class="cinture"><select name="newcintura[9]"><option value="-1"></option><option value="1">White</option><option value="2">Yellow</option><option value="3">Orange</option><option value="4">Green</option><option value="5">Blue</option><option value="6">Brown</option><option value="7">Black</option></select></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[9][0]" value="0" alt="Kata" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[9][1]" value="1" alt="Sanbon" /></td><td class="tipo"><input type="checkbox" class="styled" name="newtipo[9][2]" value="2" alt="Ippon" /></td><td class="stile"><select name="newstile[9]"><option value="1">Gojuryu</option><option value="2" selected="selected">Shitoryu</option><option value="3">Shotokan</option><option value="4">Wadoryu</option></select></td><td class="peso"><input type="text" maxlength="3"  name="newpeso[9]" value=""/></td></tr>
</table>
<div class="pulsante " style="text-align:left">
<input type="button" onclick="aggiungiCampi();" value="Add new fields" />
<br /><br>
</div>
<div class="pulsante tr" style="text-align:center">

	<input type="submit" value="Save" />
	</div>
	
</form>
<br></br>
</div>
</div>
</div>
</body>
</html>
